services:
  postgres:
    image: postgres:17

    env_file:
      - ../.env

    environment:
      POSTGRES_USER: BD2026.1
      POSTGRES_PASSWORD: BD2026.1
      POSTGRES_DB: BD2026.1

    ports:
      - "5432:5432"

    volumes:
    - ../database/DDLs/runDDLs.sql

    #revisar esse volume
